name: env_tutorial
## Triggers the workflow on when there is a push, or 
## pull request on the main branch
on: [pull_request, push]

jobs:
  rspec:
    ## The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: test-cases
        ## Reference your environment variables
        run: echo "The API key is:${{secrets.API_KEY}}"